{extends ../@layout.phtml}

{block #content}
<?php $i = 0;$before = -1; $class = sizeof($tables) ?>
{foreach $tables AS $rows}
<table class="table-{$class}">
<thead>
    {foreach $columns as $column}
    <th>{$column}</th>
    {/foreach}
</thead>
<tbody>
{foreach $rows as $num => $row}
<tr{if !$iterator->isOdd()} class="even"{/if}>
	<?php $i++ ?>
	<td>{if ($before != $row->score)}{=$i}.{/if}</td>
	<td>{=substr($row->team_name,0,35)}{if (strlen($row->team_name) > 35)}...{/if}</td>
	<td>{=$row->score}{if ($row->score == null)}0{/if}</td>
	<?php $before = $row->score ?>
</tr>
{/foreach}
</tbody>
</table>
{/foreach}
{/block}