<?php //netteCache[01]000166a:2:{s:4:"time";s:21:"0.95793600 1234994217";s:2:"df";a:1:{s:82:"/home/papi/workspace/php/intersob/document_root/../app/templates/Admin.tasks.phtml";i:1234992328;}}?><?php
// template /home/papi/workspace/php/intersob/document_root/../app/templates/Admin.tasks.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><?php echo $form ?>
<table class="table-1">
<thead>
	<tr>
		<th>Tým</th>
		<th>Splněný úkol</th>
		<th>Body</th>
		<th></th>
		<th></th>
	</tr>
</thead>
<tbody>
<?php foreach ($iterator = $_cb->its[] = new SmartCachingIterator($solutions) as $solution): ?>
<?php echo $solution ?>
<?php endforeach; array_pop($_cb->its); $iterator = end($_cb->its) ?>
</tbody>
</table><?php
}
?>