<?php //netteCache[01]000192a:2:{s:4:"time";s:21:"0.97077500 1237409013";s:2:"df";a:1:{s:107:"/mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.login.phtml";i:1237396955;}}?><?php
// template /mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.login.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><?php echo $form ?><?php
}
?>