<?php //netteCache[01]000166a:2:{s:4:"time";s:21:"0.97421700 1234131132";s:2:"df";a:1:{s:82:"/home/papi/workspace/php/intersob/document_root/../app/templates/Admin.login.phtml";i:1234131033;}}?><?php
// template /home/papi/workspace/php/intersob/document_root/../app/templates/Admin.login.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><?php echo $form ?><?php
}
?>