<?php //netteCache[01]000192a:2:{s:4:"time";s:21:"0.93290700 1237398592";s:2:"df";a:1:{s:107:"/mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.teams.phtml";i:1237396957;}}?><?php
// template /mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.teams.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><h2>Editujete tým "<?php echo $team->name ?>"</h2>

<table class="table-1">
<thead>
	<tr>
		<th>Tým</th>
		<th>Splněný úkol</th>
		<th>Body</th>
		<th></th>
		<th></th>
	</tr>
</thead>
<tbody>
<?php foreach ($iterator = $_cb->its[] = new SmartCachingIterator($solutions) as $solution): ?>
<?php echo $solution ?>
<?php endforeach; array_pop($_cb->its); $iterator = end($_cb->its) ?>
</tbody>
</table><?php
}
?>