<?php //netteCache[01]000192a:2:{s:4:"time";s:21:"0.78061900 1237396963";s:2:"df";a:1:{s:107:"/mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.tasks.phtml";i:1237396956;}}?><?php
// template /mnt/data/accounts/p/papousek/data/www/subdomains/intersob/document_root/../app/templates/Admin.tasks.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><h2>Zapsat vyřešený úkol</h2>
<?php echo $form ?>
<h2>Editovat úkoly konkrétního týmu</h2>
<?php echo $selectTeamForm ?>
<h2>Editovat naposledy vyřešené úkoly</h2>
<table class="table-1">
<thead>
	<tr>
		<th>Tým</th>
		<th>Splněný úkol</th>
		<th>Body</th>
		<th></th>
		<th></th>
	</tr>
</thead>
<tbody>
<?php foreach ($iterator = $_cb->its[] = new SmartCachingIterator($solutions) as $solution): ?>
<?php echo $solution ?>
<?php endforeach; array_pop($_cb->its); $iterator = end($_cb->its) ?>
</tbody>
</table><?php
}
?>