<?php //netteCache[01]000168a:2:{s:4:"time";s:21:"0.73594700 1234103771";s:2:"df";a:1:{s:84:"/home/papi/workspace/php/intersob/document_root/../app/templates/Admin.default.phtml";i:1234100382;}}?><?php
// template /home/papi/workspace/php/intersob/document_root/../app/templates/Admin.default.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><h1>The installation of the database has been successful done.</h1><?php
}
?>