<?php //netteCache[01]000163a:2:{s:4:"time";s:21:"0.30958200 1234524912";s:2:"df";a:1:{s:79:"/home/papi/workspace/php/intersob/document_root/../app/templates//@layout.phtml";i:1234524909;}}?><?php
// template /home/papi/workspace/php/intersob/document_root/../app/templates//@layout.phtml
?><?php $_cb = CurlyBracketsFilter::initState($template) ?><?php
if (SnippetHelper::$outputAllowed) {
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>INTERdisciplinární SOutěž Brno</title>
    <link rel="stylesheet" media="all" href="<?php echo $baseUri ?>css/main.css" type="text/css">
    <?php if ($presenter->refresh): ?>
    <script type="text/javascript"><?php $_cb->escape = "escapeJs" ?>
    	window.setInterval("window.location.reload()",10000);
    <?php $_cb->escape = "escape" ?></script>
    <?php endif ?>
</head>

<body>
<div id="content">
	<ul id="menu">
		<li><a href="<?php echo $template->{$_cb->escape}($presenter->link('Default:')) ?>" title="Výsledky">Výsledky</a>
		<li><a href="<?php echo $template->{$_cb->escape}($presenter->link('Default:tasks')) ?>" title="Stanoviště">Stanoviště</a>
		<li><a href="<?php echo $template->{$_cb->escape}($presenter->link('Default:detail')) ?>" title="Podrobné výsledky">Podrobné výsledky</a>
		<li><a href="<?php echo $template->{$_cb->escape}($presenter->link('Admin:tasks')) ?>" title="Editovat">Editovat výsledky</a>
		<?php if ($presenter->logged): ?>
		<li><a href="<?php echo $template->{$_cb->escape}($presenter->link('Admin:logout')) ?>" title="Úkoly">Odhlásit</a>
		<?php endif ?>

	</ul>
	<?php echo $template->subTemplate($content)->__toString(TRUE) ?>
</div>
</body>
</html><?php
}
?>