<?php $i = 0; $before = -1; ?>
<table class="table-1">
<thead>
	<tr>
		<th>#</th>
		<th>Tým</th>
		<th>Celkem</th>
		{foreach $tasks AS $task}
		<th class="taskID">{=$task->taskID}</th>
		{/foreach}
	</tr>
</thead>
<tbody>
{foreach $teams AS $team}
<tr>
	<?php $i++; ?>
	<td>{if $before != $team["score"]}{$i}.{/if}</td>
	<td>{=$team["teamName"]}</td>
	<td>{if !$team["score"]}0{/if}{=$team["score"]}</td>
	{foreach $team["tasks"] AS $task}
	<td class="solution{if ($task["taskAvgScore"] <= $task["taskScore"]) && ($task["taskScore"] > 0)}-over{/if}{if ($task["taskAvgScore"] > $task["taskScore"]) && ($task["taskScore"] > 0)}-lower{/if}">
		{if !$task["taskScore"]}-{/if}
		{=$task["taskScore"]}
	</td>
	<?php $before = $team["score"]; ?>
	{/foreach}
</tr>
{/foreach}
</tbody>
</table>